# Generated by Django 2.0.1 on 2019-04-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190412_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('menu_position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('menu_position',),
            },
        ),
    ]
