# Generated by Django 2.0.1 on 2019-04-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_imagecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.ImageCategory'),
        ),
    ]
