# Generated by Django 2.0.1 on 2019-04-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_imagepost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecategory',
            name='exclude_from_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
